<?php

$perguntas  = array(
    '1' => array( // chave única
        'pergunta' => 'Não é um modificador de privacidade em JAVA',
        'alternativas' => array(
            '1' => 'Protected',
            '2' => 'Procedure',
            '3' => 'Private',
            '4' => 'Public',
        ),
        'resposta' => '2',
        'dificuldade' => '1', // 1 facil, 2 medio, 3 dificil // 
    ),
    '2' => array(
        'pergunta' => 'Estrutura de dados que armazena uma coleção de elementos de tal forma que cada elemento possa ser identificado por, pelo menos, um índice ou uma chave',
        'alternativas' => array(
            '1' => 'Array',
            '2' => 'Tupla',
            '3' => 'POO',
            '4' => 'Procedure',
        ),
        'resposta' => '1',
        'dificuldade' => '1',
    ),
    '3' => array(
        'pergunta' => 'Qual do conceito de programação orientada a objetos que permite a criação de métodos com a mesma assinatura, porém com implementações diferentes?',
        'alternativas' => array(
            '1' => 'Encapsulamento',
            '2' => 'Herança',
            '3' => 'Polimorfismo',
            '4' => 'Interface',
        ),
        'resposta' => '3',
        'dificuldade' => '1',
    ),
    '4' => array(
        'pergunta' => 'Na programação orientada a objetos, pode-se definir classes sem instanciar objetos. Nestas situações, essas classes são conhecidas como',
        'alternativas' => array(
            '1' => 'Hierárquicas',
            '2' => 'Protegidas',
            '3' => 'Privadas',
            '4' => 'Abstratas',
        ),
        'resposta' => '4',
        'dificuldade' => '1',
    ),
    '5' => array(
        'pergunta' => 'Como se denomina a capacidade de ocultar dados dentro de modelos, permitindo que somente operações especializadas ou dedicadas manipulem dados ocultos?',
        'alternativas' => array(
            '1' => 'Encapsulamento',
            '2' => 'Modularização',
            '3' => 'Modificação',
            '4' => 'Classes',
        ),
        'resposta' => '1',
        'dificuldade' => '1',
    ),
    '6' => array(
        'pergunta' => 'A descrição acima está relacionada ao parâmetro da OO denominado:',
        'alternativas' => array(
            '1' => 'Reusabilidade',
            '2' => 'Modularidade',
            '3' => 'Herança',
            '4' => 'Polimorfismo',
        ),
        'resposta' => '3',
        'dificuldade' => '2',
    ),
    '7' => array(
        'pergunta' => 'A relação entre a classe "Soma" e a classe "OperacaoMatematica" é de',
        'alternativas' => array(
            '1' => 'Composição',
            '2' => 'Recursividade',
            '3' => 'Herança',
            '4' => 'Polimorfismo',
        ),
        'resposta' => '3',
        'dificuldade' => '2',
    ),
    '8' => array(
        'pergunta' => 'Considerando o conceito de Herança Múltipla na programação orientada a objetos:',
        'alternativas' => array(
            '1' => 'Permite um objeto comportar-se de forma múltipla.',
            '2' => 'É implementada em Algol, C++, Java e Python.',
            '3' => 'Corresponde, em Java, à classe Multiple Object.',
            '4' => 'Permite que uma subclasse herde de duas ou + superclasses.',
        ),
        'resposta' => '4',
        'dificuldade' => '2',
    ),
	'9' => array(
        'pergunta' => 'No que tange ao uso de serviços da API REST, a arquitetura JWT é um modelo utilizado para',
        'alternativas' => array(
            '1' => 'Conectar a uma fonte de dados remota.',
            '2' => 'Autenticar e validar o acesso ao serviço via token.',
            '3' => 'Realizar envio de dados através de arquivos JSON.',
            '4' => 'Sincronizar as informações entre cliente e servidor.',
        ),
        'resposta' => '2',
        'dificuldade' => '2',
    ),
    '10' => array(
        'pergunta' => 'São Métodos do protocolo HTTP usados em um CRUD',
        'alternativas' => array(
            '1' => 'GET, POST, PUT, DELETE',
            '2' => 'GET, POST, UPDATE, DELETE',
            '3' => 'GET, HEAD, POST, TRACE',
            '4' => 'CONNECT, POST, PUT, REMOVE',
        ),
        'resposta' => '1',
        'dificuldade' => '2',
    ),
    '11' => array(
        'pergunta' => 'MeshSmooth, Bump Map, Flat Shading são, respectivamente, tipos de:',
        'alternativas' => array(
            '1' => 'Modificador, Textura, Método de Renderização.',
            '2' => 'Modificador, Método de Renderização, Textura',
            '3' => 'Textura, Modificador, Método de Renderização.',
            '4' => 'Textura, Método de Renderização, Modificador',
        ),
        'resposta' => '1',
        'dificuldade' => '3',
    ),
    '12' => array(
        'pergunta' => 'Sobre a técnica conhecida como Z-buffer é correto aﬁrmar que:',
        'alternativas' => array(
            '1' => 'É possível realizar o cômputo das variáveis envolvidas de forma incremental.',
            '2' => 'É uma técnica muito comum de detecção de colisão.',
            '3' => 'Suas dimensões são independentes das dimensões do frame buffer',
            '4' => 'Nenhuma das alternativas acima está correta',
        ),
        'resposta' => '1',
        'dificuldade' => '3',
    ),
	'12' => array(
	    'pergunta' => 'No que diz respeito a geração de imagens por RayTracing, qual das aﬁrmações a seguir NÂO é verdadeira?',
	    'alternativas' => array(
	        '1' => 'Pode ser facilmente paralelizado',
	        '2' => 'O número de raios lançados independe do número de objetos da cena.',
	        '3' => 'Em algumas variações, o cálculo das sombras é feito a parte',
	        '4' => 'Nenhuma das alternativas acima está correta',
	    ),
	    'resposta' => '2',
	    'dificuldade' => '3',
    ),
    '13' => array(
    'pergunta' => 'Sobre a técnica de Computação Gráfica "Cohen-Sutherland", qual a sua função?',
	    'alternativas' => array(
	        '1' => 'Iluminação',
	        '2' => 'Remoção de superfícies ocultas',
	        '3' => 'Aproximação de curvas',
	        '4' => 'Recorte',
	    ),
	    'resposta' => '4',
	    'dificuldade' => '3',
    ),
    '14' => array(
    'pergunta' => 'Qual a complexidade de um algoritmo de ordenação "Merge Sort',
	    'alternativas' => array(
	        '1' => 'O(logn)',
	        '2' => 'O(nlogn)',
	        '3' => 'O(n²)',
	        '4' => 'O(n³)',
	    ),
	    'resposta' => '2',
	    'dificuldade' => '3',
    ),
    '15' => array(
    'pergunta' => 'Encontra a saída para uma instância de entrada de um problema chamando a si mesmo para resolver instâncias menores deste mesmo problema:',
	    'alternativas' => array(
	        '1' => 'Algoritmo de combinação',
	        '2' => 'Algoritmo de divisão e conquista',
	        '3' => 'Algoritmo recursivo',
	        '4' => 'Algoritmo de ordenação',
	    ),
	    'resposta' => '3',
	    'dificuldade' => '3',
    ),
    '16' => array(
    'pergunta' => 'Possuem três etapas em cada nível de recursão:',
	    'alternativas' => array(
	        '1' => 'Algoritmo de combinação',
	        '2' => 'Algoritmo de divisão e conquista',
	        '3' => 'Algoritmo recursivo',
	        '4' => 'Algoritmo de ordenação',
	    ),
	    'resposta' => '2',
	    'dificuldade' => '3',
    ),
    '17' => array(
    'pergunta' => 'O menor número possível de arestas em um grafo conexo com n vértices é:',
	    'alternativas' => array(
	        '1' => '1',
	        '2' => 'n/2',
	        '3' => 'n-1',
	        '4' => 'n',
	    ),
	    'resposta' => '3',
	    'dificuldade' => '4',
    ),
    '18' => array(
    'pergunta' => 'Filtro da mediana é Indicado para:',
	    'alternativas' => array(
	        '1' => 'Detectar bordas em imagens',
	        '2' => 'Atenuar ruído com preservação de bordas.',
	        '3' => 'Detectar formas específicas em imagens.',
	        '4' => 'Detectar tonalidades específicas em uma imagem.',
	    ),
	    'resposta' => '2',
	    'dificuldade' => '4',
    ),
    '19' => array(
    'pergunta' => 'Quais destes algoritmos de ordenação têm a classe de complexidade assintótica, no pior caso, em O(nlogn)?',
	    'alternativas' => array(
	        '1' => 'QuickSort, MergeSort, e HeapSort',
	        '2' => 'QuickSort e SelectionSort',
	        '3' => 'MergeSort e HeapSort',
	        '4' => 'QuickSort e BubbleSort',
	    ),
	    'resposta' => '3',
	    'dificuldade' => '4',
    ),
    '20' => array(
    'pergunta' => 'Os convidados presentes num jantar tomam chá ou café. 13 bebem café, 10 bebem chá e 4 bebem chá e café. Quantas pessoas tem nesse jantar?',
	    'alternativas' => array(
	        '1' => '19',
	        '2' => '27',
	        '3' => '23',
	        '4' => '15',
	    ),
	    'resposta' => '1',
	    'dificuldade' => '4',
    ),
    '20' => array(
    'pergunta' => 'Conjunto das regras e procedimentos lógicos perfeitamente definidos que levam à solução de um problema em um número finito de etapas',
	    'alternativas' => array(
	        '1' => 'algoritmos',
	        '2' => 'software educacional',
	        '3' => 'matrizes',
	        '4' => 'Nenhuma das alternativas',
	    ),
	    'resposta' => '1',
	    'dificuldade' => '4',
    ),
    '21' => array(
    'pergunta' => 'Na programação, variável é:',
	    'alternativas' => array(
	        '1' => 'O resultado de uma expressão aritmética.',
	        '2' => 'Uma posição de memória identificada.',
	        '3' => 'Uma palavra especial utilizada pela linguagem para identificar suas instruções de controle',
	        '4' => 'Nenhuma das alternativas',
	    ),
	    'resposta' => '2',
	    'dificuldade' => '1',
    ),
    '22' => array(
    'pergunta' => 'Considerando a=5, b=7, c=3 e d=9,  (a != 3 || b < 10 || c == 5) é:',
	    'alternativas' => array(
	        '1' => 'Verdadeiro',
	        '2' => 'Falso',
	        '3' => '-1',
	        '4' => 'Nenhuma das alternativas',
	    ),
	    'resposta' => '1',
	    'dificuldade' => '3',
    ),
    '23' => array(
    'pergunta' => 'Uma rede conectada à Internet possui a máscara de sub-rede 255.255.255.0. Qual o número máximo de computadores que a rede suporta?',
	    'alternativas' => array(
	        '1' => '253',
	        '2' => '254',
	        '3' => '255',
	        '4' => '65.534',
	    ),
	    'resposta' => '3',
	    'dificuldade' => '3',
    ),
    '24' => array(
    'pergunta' => 'Em relação às características do protocolo TCP é correto afirmar:',
	    'alternativas' => array(
	        '1' => 'Confirma as mensagens que já foram entregues',
	        '2' => 'É opcional que ele faça controle de congestionamento.',
	        '3' => 'Entrega as mensagens fora de ordem',
	        '4' => 'É half-duplex',
	    ),
	    'resposta' => '1',
	    'dificuldade' => '3',
    ),
    '25' => array(
    'pergunta' => 'Em relação à comandos em linguagens de programação é correto afirmar:',
	    'alternativas' => array(
	        '1' => 'Expressões aritméticas tem resultados numéricos, inteiros ou fracionários',
	        '2' => 'Expressões lógicas tem resultados verdadeiro, falso e nulo',
	        '3' => 'Declaração de variável associa um nome a um valor que, não pode ser alterado durante a execução.',
	        '4' => 'Nenhuma das alternativas',
	    ),
	    'resposta' => '1',
	    'dificuldade' => '3',
    ),
    '26' => array(
    'pergunta' => 'Na UML o diagrama de atividade é composto pelos diagramas de',
	    'alternativas' => array(
	        '1' => 'Servidores e objetos ativos',
	        '2' => 'Estado e de sequência.',
	        '3' => 'Atividades',
	        '4' => 'Brainstorm',
	    ),
	    'resposta' => '2',
	    'dificuldade' => '3',
    ),
    '27' => array(
    'pergunta' => 'Característica da qualidade que permite a fácil determinação dos antecedentes e conseqüências de todos os requisitos é a:',
	    'alternativas' => array(
	        '1' => 'Manutenção corretiva',
	        '2' => 'Precisão',
	        '3' => 'Consistência',
	        '4' => 'Rastreabilidade',
	    ),
	    'resposta' => '4',
	    'dificuldade' => '3',
    ),
    '28' => array(
    'pergunta' => 'Os componentes de uma biblioteca de software, no modelo orientado a objetos, correspondem a:',
	    'alternativas' => array(
	        '1' => 'Classes.',
	        '2' => 'Objetos',
	        '3' => 'Mensagem',
	        '4' => 'Métodos',
	    ),
	    'resposta' => '2',
	    'dificuldade' => '3',
    ),
    '29' => array(
    'pergunta' => 'NÃO é função do Kernel de um sistema operacional:',
	    'alternativas' => array(
	        '1' => 'Lançamentos na contabilidade da empresa.',
	        '2' => 'Suporte a redes locais e distribuída',
	        '3' => 'Gerência do sistema de arquivo',
	        '4' => 'Gerência dos dispositivos de E/S',
	    ),
	    'resposta' => '1',
	    'dificuldade' => '3',
    ),
    '30' => array(
    'pergunta' => 'Qual é o máximo endereçamento de memória possível do sistema operacional de 32 bits:',
	    'alternativas' => array(
	        '1' => '1Tbytes.',
	        '2' => '2Gbytes',
	        '3' => '3Gbytes',
	        '4' => '4Gbytes',
	    ),
	    'resposta' => '4',
	    'dificuldade' => '3',
    ),
    '31' => array(
    'pergunta' => 'Qual é o número mínimo de comparações necessário para encontrar o menor elemento de um conjunto qualquer não ordenado de n elementos?',
        'alternativas' => array(
            '1' => '1.',
            '2' => 'n - 1',
            '3' => 'n',
            '4' => 'n log n',
        ),
        'resposta' => '2',
        'dificuldade' => '3',
    ),
    '32' => array(
    'pergunta' => 'Um algoritmo é executado em 10 segundos para uma entrada de tamanho 50. Sendo quadrático, quanto tempo em segundos ele gastará, no mesmo computador, se a entrada tiver tamanho 100?',
        'alternativas' => array(
            '1' => '10',
            '2' => '20',
            '3' => '30',
            '4' => '40',
        ),
        'resposta' => '4',
        'dificuldade' => '4',
    ),
    '33' => array(
    'pergunta' => 'Qual a forma correta de criar um array contendo 3 strings em PHP?',
        'alternativas' => array(
            '1' => '$estados = array["SP", "PB", "BA"];',
            '2' => '$estados = {"SP", "PB", "BA"};',
            '3' => '$estados = array("SP", "PB", "BA");',
            '4' => '$estados = "SP", "PB", "BA";',
        ),
        'resposta' => '3',
        'dificuldade' => '2',
    ),
    '34' => array(
    'pergunta' => 'No PHP, caso a declaração require não puder acessar o arquivo indicado, o interpretador produz um',
        'alternativas' => array(
            '1' => 'alerta e o programa continua sua execução sem carregar o arquivo.',
            '2' => 'erro fatal e o programa é encerrado',
            '3' => 'erro fatal e o programa entra em loop',
            '4' => 'alerta e o programa é encerrado',
        ),
        'resposta' => '2',
        'dificuldade' => '2',
    ),
    '35' => array(
    'pergunta' => 'Dentre essas variáveis superglobais PHP, qual que contém informações sobre cabeçalhos, caminhos e locais de script?',
        'alternativas' => array(
            '1' => '$_SESSION',
            '2' => '$_GET',
            '3' => '$_SERVER',
            '4' => '$_REQUEST',
        ),
        'resposta' => '3',
        'dificuldade' => '2',
    ),
    '36' => array(
    'pergunta' => 'Suponha que desejamos enviar cookies de array contendo o nome de três pessoas com o nome do cookie sendo pessoa. Qual a maneira correta?',
        'alternativas' => array(
            '1' => "setcookie('pessoa[0]', 'Maria'); setcookie('pessoa[1]', 'João'); setcookie('pessoa[2]', 'José')",
            '2' => "setcookie('pessoa', ['Maria', 'João', 'José']);",
            '3' => "setcookie('pessoa', '['Maria', 'João', 'José']');",
            '4' => "$nomes = ['Maria', 'João', 'José']; setcookie('pessoa', nomes);",
        ),
        'resposta' => '1',
        'dificuldade' => '2',
    ),
    '37' => array(
    'pergunta' => 'Para concatenar a string "TRF" com a variável reg que contém o valor inteiro 3, em Java e PHP, utilizam-se, respectivamente',
        'alternativas' => array(
            '1' => 'String("TRF")+reg e str("TRF").$reg',
            '2' => '"TRF"+reg e "TRF".$reg',
            '3' => '"TRF",reg e Concat("TRF",$reg)',
            '4' => 'String.Concat("TRF",reg) e "TRF"+$reg',
        ),
        'resposta' => '2',
        'dificuldade' => '2',
    ),
    '38' => array(
    'pergunta' => '$x = 10 /*+ 2 */+ 10; Sobre essa instrução, pode-se afirmar que:',
        'alternativas' => array(
            '1' => 'ela é sintaticamente válida e $x receberá o valor 20.',
            '2' => 'ela é sintaticamente válida e $x receberá o valor 50',
            '3' => 'ela é sintaticamente válida e $x receberá o valor 10',
            '4' => 'sua execução é impossível, pois possui um erro de sintaxe.',
        ),
        'resposta' => '2',
        'dificuldade' => '2',
    ),
    '39' => array(
    'pergunta' => 'A linguagem baseada em script de uso livre (open source) e adequada para o desenvolvimento web, pois pode ser embutida em códigos HTML',
        'alternativas' => array(
            '1' => 'PHP',
            '2' => 'Angular',
            '3' => 'Python',
            '4' => 'Java',
        ),
        'resposta' => '1',
        'dificuldade' => '2',
    ),
    '40' => array(
    'pergunta' => 'A classe apresentada destina-se a teste unitário de software e pode ser melhor associada à seguinte metodologia de desenvolvimento de software:',
        'alternativas' => array(
            '1' => 'Behavior Driven Development (BDD).',
            '2' => 'Refactoring',
            '3' => 'Feature Driven Development (FDD)',
            '4' => 'Behavior Driven Development (BDD).',
        ),
        'resposta' => '4',
        'dificuldade' => '2',
    ),
    '41' => array(
    'pergunta' => 'Em laravel, v5.5, a técnica que permite compartilhar atributos de rotas, tais como middleware ou namespaces, entre várias rotas, sem a necessidade de definir esses atributos para cada rota individualmente, é:',
        'alternativas' => array(
            '1' => 'Route View',
            '2' => 'Route Match.',
            '3' => 'Sub-Domain Routing',
            '4' => 'Route Groups',
        ),
        'resposta' => '4',
        'dificuldade' => '4',
    ),
    '42' => array(
    'pergunta' => 'A principal funcionalidade desse framework é permitir ao PHP a comunicação bidirecional por meio de canais full-duplex sobre um único soquete.',
        'alternativas' => array(
            '1' => 'Symfony',
            '2' => 'Laravel',
            '3' => 'Zend',
            '4' => 'CakePHP',
        ),
        'resposta' => '1',
        'dificuldade' => '4',
    ),
    '43' => array(
    'pergunta' => 'A principal funcionalidade desse framework é permitir ao PHP a comunicação bidirecional por meio de canais full-duplex sobre um único soquete.',
        'alternativas' => array(
            '1' => 'Symfony',
            '2' => 'Laravel',
            '3' => 'Zend',
            '4' => 'CakePHP',
        ),
        'resposta' => '1',
        'dificuldade' => '4',
    ),
    '44' => array(
    'pergunta' => 'Em resposta a uma requisição AJAX, o script executando no servidor envia para o cliente, no formato JSON { "nome":"Rodrigo", "id":8723, "v":[-1,2] } como é recebida no campo do objeto XMLHttpRequest?',
        'alternativas' => array(
            '1' => 'responseString',
            '2' => 'serverResponse',
            '3' => 'responseText',
            '4' => 'JSONResponse',
        ),
        'resposta' => '3',
        'dificuldade' => '3',
    ),
    '45' => array(
    'pergunta' => 'Considerando os elementos semânticos da linguagem HTML5, os links devem ficar imediatamente no interior da tag',
        'alternativas' => array(
            '1' => '<navigation>',
            '2' => '<nav>',
            '3' => '<choose>',
            '4' => '<mark>',
        ),
        'resposta' => '2',
        'dificuldade' => '3',
    ),
    '46' => array(
    'pergunta' => 'A opção de marcador inoput que permite que essa entrada de dados seja um campo do tipo sim/não, exibindo várias opções, mas que só se aceita que uma delas seja escolhida, é a',
        'alternativas' => array(
            '1' => 'Radio',
            '2' => 'Checkbox',
            '3' => 'TrueFalseBox',
            '4' => 'Text',
        ),
        'resposta' => '1',
        'dificuldade' => '3',
    ),
    '47' => array(
    'pergunta' => 'A opção que deve ser colocada na tag body para que o arquivo de imagem possa ser utilizado como fundo da tela é',
        'alternativas' => array(
            '1' => 'background="imagem.jpg"',
            '2' => 'bg=imagem.jpg',
            '3' => 'picture="imagem.jpg"',
            '4' => 'figure=imagem.jpg',
        ),
        'resposta' => '2',
        'dificuldade' => '3',
    ),
    '48' => array(
    'pergunta' => 'Após essas linhas de código, para chamar a função setSenha da classe Usuário e passar a senha recebida criptografada com algoritmo MD5, utiliza-se a instrução',
        'alternativas' => array(
            '1' => '$usu->Senha = md5($senha)',
            '2' => '$usu.setSenha(md5($senha))',
            '3' => '$usu->Senha = $senha.setCryptography(md5)',
            '4' => '$usu.setSenha(Cryptography.md5($senha))',
        ),
        'resposta' => '1',
        'dificuldade' => '3',
    ),
    '49' => array(
    'pergunta' => 'Essa classe criada não é instanciada, apenas fornece um modelo para geração de outras classes: ',
        'alternativas' => array(
            '1' => 'Classe sobrescrita',
            '2' => 'Subclasse',
            '3' => 'Classe construtora',
            '4' => 'Classe abstrata',
        ),
        'resposta' => '4',
        'dificuldade' => '3',
    ),
    '50' => array(
    'pergunta' => 'Qual trecho de código em Java está declarando uma classe corretamente?',
        'alternativas' => array(
            '1' => 'public class clienteVip extends cliente, pessoa',
            '2' => 'public class clienteVip extends cliente implements clienteVip, pessoa',
            '3' => 'public class clienteVip extends cliente implements funcionário',
            '4' => 'public class cliente extends pessoaFisica, pessoa',
        ),
        'resposta' => '3',
        'dificuldade' => '3',
    ),
    '51' => array(
    'pergunta' => 'Na orientação a objetos, para que um atributo de uma classe C possa ser acessado apenas por qualquer método de C ou subclasses sua  visibilidade deve ser',
        'alternativas' => array(
            '1' => 'privada (private)',
            '2' => 'pública (public)',
            '3' => 'protegida (protected)',
            '4' => 'estática (static)',
        ),
        'resposta' => '3',
        'dificuldade' => '4',
    ),
    '52' => array(
    'pergunta' => 'Em um sistema desenvolvido utilizando uma linguagem orientada a objetos, a classe W estende a classe X, portanto podemos afirmar que:',
        'alternativas' => array(
            '1' => 'W é subclasse de X',
            '2' => 'X é subclasse de W',
            '3' => 'X é derivada de W',
            '4' => 'W é uma interface de X',
        ),
        'resposta' => '1',
        'dificuldade' => '3',
    ),
    '53' => array(
    'pergunta' => 'Na programação orientada a objetos, há um mecanismo que permite definir modificadores de acesso. Quando se define um atributo de uma classe com o modificador de acesso privado, significa:',
        'alternativas' => array(
            '1' => 'o acesso à classe é privado',
            '2' => 'a classe é abstrata',
            '3' => 'a classe é composta',
            '4' => 'o atributo é acessível somente aos métodos da classe',
        ),
        'resposta' => '4',
        'dificuldade' => '2',
    ),
    '54' => array(
    'pergunta' => 'Na programação orientada a objetos, a capacidade de um objeto de ser referenciado de várias formas é chamada de _________, ou seja, uma coisa com várias formas distintas.',
        'alternativas' => array(
            '1' => 'polimorfismo',
            '2' => 'abstração',
            '3' => 'resiliência',
            '4' => 'reciprociade',
        ),
        'resposta' => '1',
        'dificuldade' => '1',
    ),
    '55' => array(
    'pergunta' => 'Na linguagem JavaScript, o operador === (três sinais de igualdade) realiza a comparação apenas do:',
        'alternativas' => array(
            '1' => 'tipo dos operandos.',
            '2' => 'valor lógico dos operandos.',
            '3' => 'valor e do tipo dos operandos',
            '4' => 'valor dos operandos',
        ),
        'resposta' => '3',
        'dificuldade' => '3',
    ),
    '56' => array(
    'pergunta' => 'Na programação orientada a objetos, representa a característica que permite prover uma única interface a entidades de diferentes tipos.',
        'alternativas' => array(
            '1' => 'Herança',
            '2' => 'Encapsulamento',
            '3' => 'Reuso',
            '4' => 'Polimorfismo',
        ),
        'resposta' => '4',
        'dificuldade' => '3',
    ),
    '57' => array(
    'pergunta' => 'Assinale a forma correta para inserir JavaScript em uma página, por meio de arquivos.',
        'alternativas' => array(
            '1' => '<scipt src="file.js"></script>',
            '2' => '<source src="file.js"></source>',
            '3' => '<input src="file.js"></input>',
            '4' => 'Nenhuma das alternativas',
        ),
        'resposta' => '1',
        'dificuldade' => '4',
    ),
    '58' => array(
    'pergunta' => 'As instruções _________, do PHP 5, são utilizadas para viabilizar a saída de dados na tela.',
        'alternativas' => array(
            '1' => 'echo e print',
            '2' => 'dump e die',
            '3' => 'printf e dump',
            '4' => 'echo e die',
        ),
        'resposta' => '1',
        'dificuldade' => '1',
    ),
    '59' => array(
    'pergunta' => 'Em PHP queremos armazenar um dado booleano que indica se o usuário que está acessando o site está autenticado ou não. Para que esse valor se mantenha durante o acesso das várias páginas, é necessário que ele seja',
        'alternativas' => array(
            '1' => 'um campo de um objeto',
            '2' => 'uma variável de sessão',
            '3' => 'uma variável estática',
            '4' => 'uma interface',
        ),
        'resposta' => '2',
        'dificuldade' => '3',
    ),
    '60' => array(
    'pergunta' => 'O seletor JQuery seleciona todos os elementos que estão desativados',
        'alternativas' => array(
            '1' => '$(":disabled")',
            '2' => '$(":enabled")',
            '3' => '$(":focused")',
            '4' => '$(":refused")',
        ),
        'resposta' => '2',
        'dificuldade' => '2',
    ),
    '61' => array(
    'pergunta' => 'Sabe-se que o elemento a ser modificado é localizado pelo valor de certo atributo. O nome do atributo HTML que deve possuir o valor “demo" em document.getElementById("demo").innerHTML = "XXX";',
        'alternativas' => array(
            '1' => 'id',
            '2' => 'identifier',
            '3' => 'name',
            '4' => 'value',
        ),
        'resposta' => '1',
        'dificuldade' => '2',
    ),
    '62' => array(
    'pergunta' => 'O protocolo que é derivado da linguagem de programação Java e sua utilização é restrita a sistemas desenvolvidos em Java ou JavaScript.',
        'alternativas' => array(
            '1' => 'JSON',
            '2' => 'XML',
            '3' => 'HTML',
            '4' => 'Nenhuma das alternativas',
        ),
        'resposta' => '1',
        'dificuldade' => '3',
    ),
    '63' => array(
    'pergunta' => 'Em JQuery, o método usado para executar uma solicitação HTTP.',
        'alternativas' => array(
            '1' => '$.get()',
            '2' => '$.give()',
            '3' => '$.search()',
            '4' => 'Nenhuma das alternativas',
        ),
        'resposta' => '1',
        'dificuldade' => '3',
    ),
    '64' => array(
    'pergunta' => 'Biblioteca que ofereçe capacidade de seleção e manipulação de HTML, manipulação de CSS e requisições AJAX.',
        'alternativas' => array(
            '1' => 'JQuery',
            '2' => 'JSP',
            '3' => 'APEX',
            '4' => 'JPA',
        ),
        'resposta' => '1',
        'dificuldade' => '2',
    ),
    '65' => array(
    'pergunta' => 'Diferentemente do que ocorre com o JavaScript, as aplicações Java são executadas em:',
        'alternativas' => array(
            '1' => 'máquina virtual ou em um browser',
            '2' => 'browser',
            '3' => 'máquina virtual (JVM)',
            '4' => 'Nenhuma das alternativas',
        ),
        'resposta' => '1',
        'dificuldade' => '1',
    ),
    '66' => array(
    'pergunta' => 'O método do jQuery que permite ocultar um elemento selecionado é.',
        'alternativas' => array(
            '1' => '.show(false)',
            '2' => '.hide',
            '3' => '.display(false)',
            '4' => 'Nenhuma das alternativas',
        ),
        'resposta' => '2',
        'dificuldade' => '1',
    ),
    '67' => array(
    'pergunta' => 'Considere uma organização que adote as práticas do Guia PMBOK, 6a edição e que a estrutura organizacional adotada em um projeto seja a virtual, os grupos de trabalho devem ser organizados:',
        'alternativas' => array(
            '1' => 'em estrutura de rede, com nós nos pontos de contato com outras pessoas',
            '2' => 'de acordo com a função',
            '3' => 'de acordo com o projeto',
            '4' => 'Nenhuma das alternativas',
        ),
        'resposta' => '1',
        'dificuldade' => '4',
    ),
    '68' => array(
    'pergunta' => 'No que diz respeito a padrões de projetos, assinale a alternativa que apresenta somente padrões estruturais.',
        'alternativas' => array(
            '1' => 'Adapter, Bridge, Command, Decorator e Template.',
            '2' => 'Adapter, Command, Flyweight, Observer e Proxy.',
            '3' => 'Composite, Decorator, Singleton, Template e Proxy.',
            '4' => 'Bridge, Composite, Decorator, Facade e Proxy.',
        ),
        'resposta' => '4',
        'dificuldade' => '4',
    ),
    '69' => array(
    'pergunta' => 'O padrão de projeto utilizado pelo padrão arquitetural MVC que é responsável por fazer com que o Model informe mudanças em seu estado para as interfaces, sem conhecê-las, é o.',
        'alternativas' => array(
            '1' => 'façade.',
            '2' => 'observer.',
            '3' => 'singleton.',
            '4' => 'composite.',
        ),
        'resposta' => '2',
        'dificuldade' => '4',
    ),
    '70' => array(
    'pergunta' => 'O método adequado para remover um recurso em uma chamada REST baseada em HTTP é:',
        'alternativas' => array(
            '1' => 'GET /caminho/para/recurso.',
            '2' => 'POST /caminho/para/recurso.',
            '3' => 'PATCH /caminho/para/recurso.',
            '4' => 'DELETE /caminho/para/recurso.',
        ),
        'resposta' => '4',
        'dificuldade' => '4',
    ),
    '71' => array(
    'pergunta' => 'Considere um elemento HTML do tipo selection, cujo id é “X". Qual a opção que indica a forma correta de uma expressão para descobrir se o item na posição i foi selecionado.',
        'alternativas' => array(
            '1' => "document.selection('X').options.selected[i].",
            '2' => "document.getElementById('X').options.selected[i]",
            '3' => "document.getElementById('X').options[i].selected",
            '4' => "document.element('X').options.selected[i]",
        ),
        'resposta' => '3',
        'dificuldade' => '2',
    ),
    '72' => array(
    'pergunta' => 'Ao desenvolver uma aplicação cliente Web, o programador precisa mostrar um aviso quando a página requisitada tem o acesso proibido. Qual seria o código de resposta?',
    'alternativas' => array(
            '1' => '404',
            '2' => '201',
            '3' => '500',
            '4' => '403',
        ),
        'resposta' => '4',
        'dificuldade' => '2',
    ),
    '73' => array(
    'pergunta' => 'Não é um tipo de Respostas no protocolo HTTP',
    'alternativas'=> array(
            '1' => '2xx - Sucesso',
            '2' => '3xx - Redirecionamento',
            '3' => '4xx - Erro do cliente',
            '4' => '6xx - Erro do Servidor',
        ),
        'resposta' => '6',
        'dificuldade' => '2',
    ),
    '74' => array(
    'pergunta' => 'O uso de funções que previnem certos comportamentos anômalos no processamento de efeitos.',
    'alternativas' => array(
            '1' => 'Callback parameter',
            '2' => 'Event parameter',
            '3' => 'Message parameter',
            '4' => 'Trigger parameter',
        ),
        'resposta' => '1',
        'dificuldade' => '3',
    ),
    '75' => array(
    'pergunta' => 'Quais os métodos disponíveis na classe HTTPServlet?.',
    'alternativas' => array(
            '1' => 'getNome(), doGet(), doPost(), doHTTP()',
            '2' => 'init(), service(), destroy()',
            '3' => 'doSend(), doGet(), doPost(), destroy()',
            '4' => 'response(), doGet(), doPost(), destroy()',
        ),
        'resposta' => '2',
        'dificuldade' => '4',
    ),
    '76' => array(
    'pergunta' => 'Uma tag utilizada pelo CSS para definir uma correspondência entre um documento e um recurso externo.', 
    'alternativas' => array(
            '1' => 'border',
            '2' => 'head',
            '3' => 'link',
            '4' => 'style',
        ),
        'resposta' => '3',
        'dificuldade' => '4',
    ),
    '77' => array(
    'pergunta' => 'A vulnerabilidade que ocorre quando a aplicação web permite que páginas privadas sejam acessadas sem a devida autenticação de usuários anônimos e de usuários autenticados denomina-se' ,
    'alternativas'=> array(
            '1' => 'falha na restrição de acesso a URL.',
            '2' => 'vulnerabilidade XSS',
            '3' => 'armazenamento criptográfico inseguro',
            '4' => 'quebra de autenticação e da gestão de sessão',
        ),
        'resposta' => '1',
        'dificuldade' => '4',
    ),
    '78' => array(
    'pergunta' => 'O serviço Angular JS _____ é usado para fazer uma chamada Ajax para o servidor.',
    'alternativas' => array(
            '1' => '$http',
            '2' => '$get',
            '3' => '$httpRequest',
            '4' => '$post',
        ),
        'resposta' => '1',
        'dificuldade' => '1',
    ),
    '79' => array(
    'pergunta' => 'AngularJS é um framework JavaScript, também referenciado como uma biblioteca escrita em JavaScript. Esse framework permite o uso de.',
    'alternativas' => array(
            '1' => 'expressões dentro de uma diretiva: ng-bind = "expression"',
            '2' => 'expressões dentro de colchetes duplos, [[expression.]]',
            '3' => 'filtros que devem ser adicionados às expressões por meio do caractere cerquilha (#)',
            '4' => 'XML com diretivas xsd, como xsd-app, xsd-model e xsd-bind',
        ),
        'resposta' => '1',
        'dificuldade' => '2',
    ),
    '80' => array(
    'pergunta' => 'Existem duas grandes estratégias que dividem as linguagens de programação conhecidas no mercado. Marque a alternativa que indica corretamente o nome dessas duas estratégias.',
    'alternativas' => array(
            '1' => 'Compilação e Tradução',
            '2' => 'Recursão e Interpretação',
            '3' => 'Tradução e Recursão',
            '4' => 'Interpretação e Compilação',
        ),
        'resposta' => '4',
        'dificuldade' => '2',
    ),
    '81' => array(
    'pergunta' => 'Em PL/SQL, após a execução de um comando UPDATE, o cursor implícito SQL%FOUND retornará verdadeiro se:',
    'alternativas' => array(
            '1' => 'a coluna alterada já possuía o valor que iria receber.',
            '2' => 'o valor informado para alguma coluna não puder ser atribuído',
            '3' => 'alguma linha tiver sido alterada',
            '4' => 'nenhuma linha tiver sido alterada',
        ),
        'resposta' => '3',
        'dificuldade' => '2',
    ),
    '82' => array(
    'pergunta' => 'Em bancos de dados relacionais, a forma normal que estabelece que os domínios de seus atributos devem ser atômicos (admitir um valor único para cada atributo) é a',
    'alternativas' => array(
            '1' => 'Primeira Forma Normal.',
            '2' => 'Segunda Forma Normal.',
            '3' => 'Terceira Forma Normal.',
            '4' => 'Quarta Forma Normal.',
        ),
        'resposta' => '1',
        'dificuldade' => '2',
    ),
    '83' => array(
    'pergunta' => 'Em relação aos algoritmos as funções abaixo convertem um dado número real em inteiro, marque a alternativa VERDADEIRA:',
    'alternativas' => array(
            '1' => 'abs e round',
            '2' => 'abs e tier',
            '3' => 'round e tier',
            '4' => 'round e trunc',
        ),
        'resposta' => '4',
        'dificuldade' => '2',
    ),
    '84' => array(
    'pergunta' => 'Java possui um conjunto de tipos de dados conhecidos como primitivos, dos quais NÃO faz parte o tipo',
    'alternativas' => array(
            '1' => 'short',
            '2' => 'long',
            '3' => 'string',
            '4' => 'byte',
        ),
        'resposta' => '3',
        'dificuldade' => '2',
    ),
    '85' => array(
    'pergunta' => 'No modelo relacional de bancos de dados, quando se especifica, por exemplo, que os valores de um determinado atributo devem se situar entre os valores 200 e 5000, está se especificando seu(sua)',
    'alternativas' => array(
            '1' => 'cardinalidade',
            '2' => 'ordenação',
            '3' => 'domínio',
            '4' => 'herança',
        ),
        'resposta' => '3',
        'dificuldade' => '2',
    ),
    '86' => array(
    'pergunta' => 'Na plataforma Microsoft COM (Component Object Model), todos os componentes devem implementar a interface:',
    'alternativas'=> array(
            '1' => 'IObject',
            '2' => 'IUnknown',
            '3' => 'IDispatch',
            '4' => 'IOleObject',
        ),
        'resposta' => '2',
        'dificuldade' => '2',
    ),
    '87' => array(
    'pergunta' => 'Uma das propriedades básicas de uma transação em um banco de dados relacional estabelece que cada transação não deve sofrer interferência de outras transações em execução no banco de dados',
    'alternativas' => array(
            '1' => 'durabilidade',
            '2' => 'isolamento',
            '3' => 'consistência',
            '4' => 'integridade',
        ),
        'resposta' => '2',
        'dificuldade' => '2',
    ),
    '88' => array(
    'pergunta' => 'Assinale a opção que apresenta o método HTTP que envia dados, colocando-os no corpo da mensagem, e deixa a URI separada dos dados que serão enviados.',
    'alternativas' => array(
            '1' => 'HEAD',
            '2' => 'PUT',
            '3' => 'POST',
            '4' => 'GET',
        ),
        'resposta' => '3',
        'dificuldade' => '2',
    ),
    '89' => array(
    'pergunta' => 'De acordo com a especificação dos Portlets 2.0 (JSR 286), a interface PortletSession permite o armazenamento de objetos nos escopos',
    'alternativas' => array(
            '1' => 'APPLICATION_SCOPE e PORTLET_SCOPE.',
            '2' => 'APPLICATION_SCOPE e SERVER_SCOPE',
            '3' => 'SERVER_SCOPE e PORTLET_SCOPE',
            '4' => 'CLUSTER_SCOPE e APPLICATION_SCOPE',
        ),
        'resposta' => '1',
        'dificuldade' => '4',
    ),
    '90' => array(
    'pergunta' => 'Um usuário implementou uma rotina de um fatorial, e passou para essa rotina um parâmetro com o valor 6, mas deseja receber, após a execução da rotina o valor 6!. Para isso, a passagem de parâmetro deverá ser por',
    'alternativas' => array(
            '1' => 'escopo.',
            '2' => 'hashing.',
            '3' => 'valor.',
            '4' => 'referência.',
        ),
        'resposta' => '4',
        'dificuldade' => '4',
    ),
    '91' => array(
    'pergunta' => 'Caso o driver JDBC não esteja disponível na aplicação e não exista o banco de dados trf3, as exceções que deverão ser tratadas nas lacunas I e II são, correta e respectivamente:',
    'alternativas' => array(
            '1' => 'NullPointerExceptionException e DatabaseException.',
            '2' => 'DriverNotFoundException e MySQLException.',
            '3' => 'JDBCDriverException e DatabaseException.',
            '4' => 'ClassNotFoundException e SQLException.',
        ),
        'resposta' => '4',
        'dificuldade' => '4',
    ),
    '92' => array(
    'pergunta' => 'Em relação as funções de saída nos algoritmos e JAVA respectivamente, marque a alternativa CORRETA:',
    'alternativas' => array(
            '1' => 'enquanto e system.out.print.',
            '2' => 'escreva e write.',
            '3' => 'enquanto e while.',
            '4' => 'escreva e system.out.print.',
        ),
        'resposta' => '4',
        'dificuldade' => '1',
    ),
    '93' => array(
    'pergunta' => 'No PL/SQL, a diretiva NOCOPY é utilizada para:',
    'alternativas' => array(
            '1' => 'indicar que o parâmetro de um procedimento deve ser passado por referência.',
            '2' => 'mover o conteúdo de uma tabela para outra em vez de manter uma cópia.',
            '3' => 'fornecer acesso direto às tabelas do banco de dados, em vez de uma cópia delas..',
            '4' => 'indicar que o parâmetro de um procedimento deve ser passado por valor.',
        ),
        'resposta' => '1',
        'dificuldade' => '4',
    ),
    '94' => array(
    'pergunta' => 'Para o código estar correto, as lacunas i e li devem ser, respectiva e corretamente, preenchidas por',
    'alternativas' => array(
            '1' => 'mysqli connect — SQLException',
            '2' => 'PDOConnect — PDOException',
            '3' => 'mysqli connect — Exception',
            '4' => 'new PDO — PDOException',
        ),
        'resposta' => '4',
        'dificuldade' => '4',
    ),
    '95' => array(
    'pergunta' => 'Em relação aos delimitadores de blocos em JAVA, marque a alternativa VERDADEIRA',
    'alternativas' => array(
            '1' => '“ [ e ] ”',
            '2' => ' “ { ” e “ } ”',
            '3' => '“ [ ” e “ ] ”',
            '4' => ' “ ( ” e “ ) ”',
        ),
        'resposta' => '2',
        'dificuldade' => '3',
    ),
    '96' => array(
    'pergunta' => 'No contexto de microsserviços, trata-se de uma abstração da arquitetura web. Consiste em princípios quando seguidos, permitem a criação de um projeto com interfaces bem definidas, permitindo que aplicações se comuniquem.',
    'alternativas' => array(
            '1' => 'SDK',
            '2' => 'JSON-RPC',
            '3' => 'XML-RPC',
            '4' => 'REST API.',
        ),
        'resposta' => '4',
        'dificuldade' => '4',
    ),
    '97' => array(
    'pergunta' => 'Java possui um conjunto de tipos de dados conhecidos como primitivos, dos quais NÃO faz parte o tipo.', 
    'alternativas' => array(
            '1' => 'short',
            '2' => 'string',
            '3' => 'float','alternativas'
            '4' => 'byte',
        ),
        'resposta' => '2',
        'dificuldade' => '1',
    ),
    '98' => array(
    'pergunta' => 'Em relação às funções de array do PHP 5 ou superior, é correto afirmar',
    'alternativas' => array(
            '1' => 'A função array_reduce permuta as chaves e valores associados em um array',
            '2' => 'A função array_splice extrai um subarray do array informado',
            '3' => 'A função array_combine cria um novo array mesclando o conteúdo de dois arrays',
            '4' => 'A função array_walk aplica uma determinada função em cada elemento de um array',
        ),
        'resposta' => '4',
        'dificuldade' => '1',
    ),
    '99' => array(
    'pergunta' => '________ é uma API utilizada pela tecnologia de apresentação Ajax e fornece a recuperação de dados de uma URL, em qualquer formato textual, sem que seja necessário atualizar completamente a página apresentada ao usuário',
    'alternativas' => array(
            '1' => 'XMLHttpRequest',
            '2' => 'PostHttpRequest',
            '3' => 'XMLRequest',
            '4' => 'Nenhuma das alternativas',
        ),
        'resposta' => '1',
        'dificuldade' => '2',
    ),
    '100' => array(
    'pergunta' => 'Em relação à sobrecarga de operadores em C#, é INCORRETO afirmar:',
    'alternativas' => array(
            '1' => 'A precedência e a associatividade dos operadores sobrecarregados são redefinidas pelo programador',
            '2' => 'Os operadores são declarados públicos',
            '3' => 'Os operadores são declarados estáticos',
            '4' => 'Nenhuma das alternativas',
        ),
        'resposta' => '1',
        'dificuldade' => '3',
    ),



);

echo json_encode($perguntas);